This markdown reads the 0.25 log2FC, BH, for all tissues and generates figure 
3A (overview of DEG).

It plots the average of DEGs across clusters. Keeps the record of total number of DEGs represented in DEGs in each sex-vax-time.

Load packages.
```{r}
library(ggplot2)
```

Load DEG data.
```{r}
setwd("C:/Users/budha/Documents/R/YF_complete/YF_report_10")

load("dLN_DEG_list.rda")
load("PBMC_DEG_list.rda")
load("spleen_DEG_list.rda")
load("ndLN_DEG_list.rda")
```

Extract information from the DEG lists.
```{r}
# order the entries in the DEG lists for the representation
ord <- c(1,5,9,13,17,3,7,11,15,19,2,6,10,14,18,4,8,12,16,20) 
#        male        female       male         female
#        good vax    good vax     bad vax      bad vax

# dLN first
dLN_desize_up <- c()
dLN_demag_up <- c()
dLN_clustno_up <- c()
dLN_desize_down <- c()
dLN_demag_down <- c()
dLN_clustno_down <- c()

for (i in 1:20) {
  p1 <- dLN_DEG_list[[i]]
  p1_up <- p1[which(p1$LFC_sh > 0),]
  p1_down <- p1[which(p1$LFC_sh < 0),]
  
  dLN_desize_up <- c(dLN_desize_up, dim(p1_up)[1])
  dLN_demag_up <- c(dLN_demag_up, mean(p1_up$LFC_sh))
  dLN_clustno_up <- c(dLN_clustno_up, length(unique(p1_up$cluster)))
  
  dLN_desize_down <- c(dLN_desize_down, dim(p1_down)[1])
  dLN_demag_down <- c(dLN_demag_down, mean(p1_down$LFC_sh))
  dLN_clustno_down <- c(dLN_clustno_down, length(unique(p1_down$cluster)))
}

dLN_desize_up <- dLN_desize_up[ord]
dLN_demag_up <- dLN_demag_up[ord]
dLN_clustno_up <- dLN_clustno_up[ord]

dLN_desize_down <- dLN_desize_down[ord]
dLN_demag_down <- dLN_demag_down[ord]
dLN_clustno_down <- dLN_clustno_down[ord]

# PBMC 
PBMC_desize_up <- c()
PBMC_demag_up <- c()
PBMC_clustno_up <- c()
PBMC_desize_down <- c()
PBMC_demag_down <- c()
PBMC_clustno_down <- c()

for (i in 1:20) {
  p1 <- PBMC_DEG_list[[i]]
  p1_up <- p1[which(p1$LFC_sh > 0),]
  p1_down <- p1[which(p1$LFC_sh < 0),]
  
  PBMC_desize_up <- c(PBMC_desize_up, dim(p1_up)[1])
  PBMC_demag_up <- c(PBMC_demag_up, mean(p1_up$LFC_sh))
  PBMC_clustno_up <- c(PBMC_clustno_up, length(unique(p1_up$cluster)))
  
  PBMC_desize_down <- c(PBMC_desize_down, dim(p1_down)[1])
  PBMC_demag_down <- c(PBMC_demag_down, mean(p1_down$LFC_sh))
  PBMC_clustno_down <- c(PBMC_clustno_down, length(unique(p1_down$cluster)))
}
PBMC_desize_up <- PBMC_desize_up[ord]
PBMC_demag_up <- PBMC_demag_up[ord]
PBMC_clustno_up <- PBMC_clustno_up[ord]

PBMC_desize_down <- PBMC_desize_down[ord]
PBMC_demag_down <- PBMC_demag_down[ord]
PBMC_clustno_down <- PBMC_clustno_down[ord]

#spleen
spleen_desize_up <- c()
spleen_demag_up <- c()
spleen_clustno_up <- c()
spleen_desize_down <- c()
spleen_demag_down <- c()
spleen_clustno_down <- c()

for (i in 1:20) {
  p1 <- spleen_DEG_list[[i]]
  p1_up <- p1[which(p1$LFC_sh > 0),]
  p1_down <- p1[which(p1$LFC_sh < 0),]
  
  spleen_desize_up <- c(spleen_desize_up, dim(p1_up)[1])
  spleen_demag_up <- c(spleen_demag_up, mean(p1_up$LFC_sh))
  spleen_clustno_up <- c(spleen_clustno_up, length(unique(p1_up$cluster)))
  
  spleen_desize_down <- c(spleen_desize_down, dim(p1_down)[1])
  spleen_demag_down <- c(spleen_demag_down, mean(p1_down$LFC_sh))
  spleen_clustno_down <- c(spleen_clustno_down, length(unique(p1_down$cluster)))
}
spleen_desize_up <- spleen_desize_up[ord]
spleen_demag_up <- spleen_demag_up[ord]
spleen_clustno_up <- spleen_clustno_up[ord]

spleen_desize_down <- spleen_desize_down[ord]
spleen_demag_down <- spleen_demag_down[ord]
spleen_clustno_down <- spleen_clustno_down[ord]

#ndLN
ndLN_desize_up <- c()
ndLN_demag_up <- c()
ndln_clustno_up <- c()

ndLN_desize_down <- c()
ndLN_demag_down <- c()
ndln_clustno_down <- c()

for (i in 1:20) {
  p1 <- ndLN_DEG_list[[i]]
  p1_up <- p1[which(p1$LFC_sh > 0),]
  p1_down <- p1[which(p1$LFC_sh < 0),]
  
  ndLN_desize_up <- c(ndLN_desize_up, dim(p1_up)[1])
  ndLN_demag_up <- c(ndLN_demag_up, mean(p1_up$LFC_sh))
  ndln_clustno_up <- c(ndln_clustno_up, length(unique(p1_up$cluster)))
  
  ndLN_desize_down <- c(ndLN_desize_down, dim(p1_down)[1])
  ndLN_demag_down <- c(ndLN_demag_down, mean(p1_down$LFC_sh))
  ndln_clustno_down <- c(ndln_clustno_down, length(unique(p1_down$cluster)))
}
ndLN_desize_up <- ndLN_desize_up[ord]
ndLN_demag_up <- ndLN_demag_up[ord]
ndln_clustno_up <- ndln_clustno_up[ord]

ndLN_desize_down <- ndLN_desize_down[ord]
ndLN_demag_down <- ndLN_demag_down[ord]
ndln_clustno_down <- ndln_clustno_down[ord]
```
Plot.
```{r}
#dLN_ave_up <-
#dLN_ave_down <- "black", "white", "#1d8104", "magenta"
  
  
plotdata <- data.frame(Xcoor <- c(1:20,1:20,1:20,1:20,1:20,1:20,1:20,1:20), 
                       Ycoor <- c(rep(8,20),rep(7,20),rep(6,20),rep(5,20),rep(4,20),rep(3,20),rep(2,20),rep(1,20)),
                       desize <- c(dLN_desize_up, dLN_desize_down, PBMC_desize_up, PBMC_desize_down, 
                                   spleen_desize_up, spleen_desize_down, ndLN_desize_up, ndLN_desize_down),           
                       demag <- c(dLN_demag_up, dLN_demag_down, PBMC_demag_up, PBMC_demag_down, 
                                  spleen_demag_up, spleen_demag_down, ndLN_demag_up, ndLN_demag_down))
colnames(plotdata) <- c("Xcoor", "Ycoor", "desize", "demag")
plotdata$demag[which(is.nan(plotdata$demag))] <- 0

for (k in 1:dim(plotdata)[1]) {
  if (plotdata$demag[k] > 2) {
    plotdata$demag[k] <- 2
  }
  if (plotdata$demag[k] < -2) {
    plotdata$demag[k] <- -2
  }
}

fig <- ggplot(plotdata,aes(Xcoor,Ycoor, size=desize)) +
  geom_hline(yintercept = c(1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5)) + geom_vline(xintercept = ((1:20)+.5)) +
  geom_point(aes(colour=demag), shape = 15) + scale_size_area(max_size = 12) +
  geom_point(shape = 0,colour = "black") + 
  scale_color_gradientn(colours = c("#1d8104", "white", "magenta")) + theme_bw() + ylim(0,9) +
  theme(panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank())    # Remove minor grid lines)
```
Plot averaged.
```{r}
dLN_ave_up <- dLN_desize_up/dLN_clustno_up
dLN_ave_down <- dLN_desize_down/dLN_clustno_down
PBMC_ave_up <- PBMC_desize_up/PBMC_clustno_up
PBMC_ave_down <- PBMC_desize_down/PBMC_clustno_down
spleen_ave_up <- spleen_desize_up/spleen_clustno_up
spleen_ave_down <- spleen_desize_down/spleen_clustno_down
ndLN_ave_up <- ndLN_desize_up/ndln_clustno_up
ndLN_ave_down <- ndLN_desize_down/ndln_clustno_down

clust_matrix <- rbind(dLN_clustno_up, dLN_clustno_down, PBMC_clustno_up, PBMC_clustno_down,
                      spleen_clustno_up, spleen_clustno_down, ndln_clustno_up, ndln_clustno_down)
clust_matrix <- as.data.frame(clust_matrix)

plotdata <- data.frame(Xcoor <- c(1:20,1:20,1:20,1:20,1:20,1:20,1:20,1:20), 
                       Ycoor <- c(rep(8,20),rep(7,20),rep(6,20),rep(5,20),rep(4,20),rep(3,20),rep(2,20),rep(1,20)),
                       desize <- c(dLN_ave_up, dLN_ave_down, PBMC_ave_up, PBMC_ave_down, 
                                   spleen_ave_up, spleen_ave_down, ndLN_ave_up, ndLN_ave_down),           
                       demag <- c(dLN_demag_up, dLN_demag_down, PBMC_demag_up, PBMC_demag_down, 
                                  spleen_demag_up, spleen_demag_down, ndLN_demag_up, ndLN_demag_down))
colnames(plotdata) <- c("Xcoor", "Ycoor", "desize", "demag")

fig <- ggplot(plotdata,aes(Xcoor,Ycoor, size=desize)) +
  geom_hline(yintercept = c(1,2,3,4,5,6,7,8)) + geom_vline(xintercept = 1:20) +
  geom_point(aes(colour=demag), shape = 15) + scale_size_area(max_size = 20) +
  geom_point(shape = 0,colour = "black") + 
  scale_color_gradientn(colours = c("#1d8104", "white", "magenta")) + theme_bw() + ylim(0.8,8.5) +
  theme(panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank())    # Remove minor grid lines)
```